### ISSUE TITLE
Fill out Readme file to include all basic commands

### ISSUE THREAD

**Issue by Danjar27** [software-espe/club-site#12]

**Comment by Alan1108** [comment]
Tienes los comandos basicos?
No tengo el contexto de toda la app 🤕

**Comment by Danjar27** [comment]
@Alan1108 Basically, just: 

To start
- npm install 
- npm prepare

Validate format and functionality:
- npm run validate

Run all unit tests:
- npm run test

Create a dev server and start coding:
- npm run dev

That's all we have for now

**Comment by Danjar27** [comment]
@Alan1108 but this is actually supposed to be @listerineh job. My bad

**Comment by Danjar27** [comment]
@abigailscl
