### ISSUE TITLE
Create a database of currently enrolled club members

### ISSUE THREAD

**Issue by Danjar27** [software-espe/club-site#7]
As a team, we want a database containing all current club members 'info.

 Since we are going to use firebase as our main DDBB, we want this in a JSON file, with following structure:

```
{
    name: string,
    start_date?: Date,
    socials: {
        linkedin?: string,
        whatsapp?: string,
        telegram?: string,
        twitter?: string
    },
    status: member | staff | candidate 
}
```

**Comment by abigailscl** [comment]
Collect data in: https://docs.google.com/spreadsheets/d/1Fvbibs-MhWRAyKu8u1IdDLu84wPbUXTdbH0kEAzkMy0/edit#gid=0
